services:
#  node:
#    image: node:18-alpine
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./src:/home/node/app
#    working_dir: /home/node/app/
#    command: sh -c "npm run dev"
#    depends_on:
#      - db
#    env_file:
#      - ./src/.env
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MONGO_INITDB_DATABASE: "${DB_NAME}"
    ports:
      - "${DB_PORT}:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db
    logging:
      driver: none

networks:
  default:
    driver: "bridge"
