name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.1.0
          run_install: false

      - name: Install dependencies
        run: cd apps/web && pnpm install

      - name: Build
        run: cd apps/web && pnpm build
